# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

BOX_IMAGE = "ol7-latest"
BOX_URL = "https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box"

# Name of the VM and the hostname inside
NAME1 = "LiquiBase"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "LiquiBase"

    config.vm.define "lb" do |lb|
      lb.vm.network "private_network", :auto_network => true
      lb.vm.box = BOX_IMAGE
      lb.vm.box_url = BOX_URL
      lb.vm.hostname = NAME1
      
    # VM Customization
      lb.vm.provider "virtualbox" do |v|
        v.customize [ "modifyvm", :id, "--memory", 1024 ]
        v.customize [ "modifyvm", :id, "--cpus", 2 ]
        v.customize [ "modifyvm", :id, "--paravirtprovider", "kvm" ]
        v.customize [ "modifyvm", :id, "--name", NAME1 ]

      #lb.vm.network "forwarded_port", guest: 5901, host: 59017
      #lb.vm.network "forwarded_port", guest: 5432, host: 54321

      lb.vm.synced_folder "/Users/bocurtis/Downloads", "/Test_Software"

      lb.vm.provision "provision_lb", type: "shell", path: "install.sh"
    end
  end
end