# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

BOX_IMAGE = "ol7-latest"
BOX_URL = "https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box"

# Name of the VM and the hostname inside
NAME1 = "GG19c-BigData"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "gg19bd"

    config.vm.define "gg" do |gg|
      gg.vm.box = BOX_IMAGE
      gg.vm.box_url = BOX_URL
      gg.vm.hostname = NAME1
      
    # VM Customization
      gg.vm.provider "virtualbox" do |v|
        v.customize [ "modifyvm", :id, "--memory", 1024 ]
        v.customize [ "modifyvm", :id, "--cpus", 2 ]
        v.customize [ "modifyvm", :id, "--paravirtprovider", "kvm" ]
        v.customize [ "modifyvm", :id, "--name", NAME1 ]

      gg.vm.network "forwarded_port", guest: 1521, host: 15214
      gg.vm.network "forwarded_port", guest: 5901, host: 59014

      gg.vm.synced_folder "/Users/bocurtis/Build_Software/zip_files/", "/Test_Software"

      gg.vm.provision "provision_gg", type: "shell", path: "scripts/GGinstall.sh", env:
      {
        "OGG_SHIPHOME"          => "OGG_BigData_Linux_x64_19.1.0.0.5.zip",
        "CLIENT_SHIPHOME_19C"   => "instantclient-basic-linux.x64-19.3.0.0.0dbru.zip",
        "ORA_INVENTORY"		      => "/opt/app/oraInventory",
        "ORACLE_BASE" 		      => "/opt/app/oracle",
        "ORACLE_HOME"           => "/opt/app/oracle/product/19.1.0/oggcore_19bd",
        "TNS_ADMIN"             => "/usr/lib/oracle/19.8/client64/lib/network/admin",
        "OGG_HOME" 		          => "/opt/app/oracle/product/19.1.0/oggcore_19bd",
        "LD_LIBRARY_PATH"        => "/usr/lib/oracle/19.8/client64/lib",
        "DB_VERSION"            => "ORA19c"
      }
    end
  end
end
