# vi: set ft=ruby :
require 'yaml'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

#-----------------------------------------
# Variables
#-----------------------------------------
params = YAML.load_file './config/variables.yaml'

# Shared
var_box_image         = params['shared']['box']
var_box_url           = params['shared']['url']
var_name              = params['env']['name']
var_host_name         = params['env']['hostname']

#-------------------------------------------
# set virtual machine specific items
#-------------------------------------------

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.network "private_network", type: "dhcp"

  config.vm.define "hvr57" do |hvr|
    hvr.vm.box = var_box_image
    hvr.vm.box_url = var_box_url
    hvr.vm.hostname = var_name

    hvr.vm.provider "virtualbox" do |v|
      v.name=var_name
      v.memory = 1024
      v.cpus = 2
    end

    hvr.vm.hostname = var_host_name
    
  # Enable ssh password authentication
    hvr.vm.provision "shell", inline: <<-SHELL
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
      /bin/systemctl restart sshd
    SHELL

  end
end